// =============================================================================
// OPE TESTING STORE - PRODUCT DATABASE
// 100+ Realistic Products with Full OPE Metadata
// =============================================================================

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  rating: number;
  reviewCount: number;
  inventory: number;
  description: string;
  category: 'food' | 'grocery' | 'pharmacy' | 'home' | 'electronics' | 'fashion';
  subcategory: string;
  tags: string[];
  canonicalType: string;
  image: string;
  unit?: string;
  nutritionInfo?: string;
  warnings?: string;
}

// =============================================================================
// FOOD CATEGORY (20 products)
// =============================================================================

const foodProducts: Product[] = [
  {
    id: 'food-001',
    name: 'Fresh Italian Pasta Tagliatelle',
    brand: 'La Pasta Fresca',
    price: 4.99,
    originalPrice: 5.99,
    discount: 17,
    rating: 4.7,
    reviewCount: 342,
    inventory: 45,
    description: 'Handmade fresh pasta made with durum wheat semolina and free-range eggs. Perfect al dente texture in just 3 minutes.',
    category: 'food',
    subcategory: 'pasta',
    tags: ['italian', 'fresh', 'dinner', 'quick-cook', 'handmade'],
    canonicalType: 'pasta',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=400&h=400&fit=crop',
    unit: '500g',
  },
  {
    id: 'food-002',
    name: 'Marinara Tomato Sauce',
    brand: 'Nonna Rosa',
    price: 3.49,
    rating: 4.8,
    reviewCount: 521,
    inventory: 78,
    description: 'Traditional Italian marinara sauce made with San Marzano tomatoes, fresh basil, and extra virgin olive oil.',
    category: 'food',
    subcategory: 'sauces',
    tags: ['italian', 'tomato', 'pasta-sauce', 'traditional'],
    canonicalType: 'pasta_sauce',
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400&h=400&fit=crop',
    unit: '680g',
  },
  {
    id: 'food-003',
    name: 'Parmigiano Reggiano DOP',
    brand: 'Consorzio',
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    rating: 4.9,
    reviewCount: 876,
    inventory: 32,
    description: 'Authentic 24-month aged Parmigiano Reggiano from Emilia-Romagna. DOP certified.',
    category: 'food',
    subcategory: 'cheese',
    tags: ['italian', 'cheese', 'aged', 'premium', 'pasta-topping'],
    canonicalType: 'cheese',
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop',
    unit: '200g',
  },
  {
    id: 'food-004',
    name: 'Artisan Sourdough Bread',
    brand: 'Urban Bakery',
    price: 5.49,
    rating: 4.6,
    reviewCount: 234,
    inventory: 28,
    description: 'Slow-fermented sourdough with crispy crust and soft, tangy interior. Made with organic flour.',
    category: 'food',
    subcategory: 'bread',
    tags: ['artisan', 'sourdough', 'organic', 'breakfast'],
    canonicalType: 'bread',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
    unit: '1 loaf',
  },
  {
    id: 'food-005',
    name: 'Premium Brioche Burger Buns',
    brand: 'Bakers Choice',
    price: 4.29,
    rating: 4.5,
    reviewCount: 189,
    inventory: 56,
    description: 'Soft, buttery brioche buns perfect for gourmet burgers. Sesame seed topped.',
    category: 'food',
    subcategory: 'bread',
    tags: ['burger', 'buns', 'brioche', 'grilling'],
    canonicalType: 'burger_buns',
    image: 'https://images.unsplash.com/photo-1586816001966-79b736744398?w=400&h=400&fit=crop',
    unit: '6 pack',
  },
  {
    id: 'food-006',
    name: 'Angus Beef Burger Patties',
    brand: 'Prime Cuts',
    price: 11.99,
    originalPrice: 14.99,
    discount: 20,
    rating: 4.7,
    reviewCount: 432,
    inventory: 24,
    description: '100% Angus beef patties, 80/20 lean-to-fat ratio for juicy, flavorful burgers.',
    category: 'food',
    subcategory: 'meat',
    tags: ['beef', 'burger', 'angus', 'grilling', 'protein'],
    canonicalType: 'burger_patties',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=400&fit=crop',
    unit: '4 x 150g',
  },
  {
    id: 'food-007',
    name: 'All-Beef Hot Dogs',
    brand: 'Grill Master',
    price: 6.99,
    rating: 4.4,
    reviewCount: 298,
    inventory: 67,
    description: 'Premium all-beef frankfurters with natural casing. Perfect snap when you bite.',
    category: 'food',
    subcategory: 'meat',
    tags: ['hot-dog', 'beef', 'grilling', 'bbq'],
    canonicalType: 'hot_dogs',
    image: 'https://images.unsplash.com/photo-1612392062126-47bf615c8679?w=400&h=400&fit=crop',
    unit: '8 pack',
  },
  {
    id: 'food-008',
    name: 'Classic Hot Dog Buns',
    brand: 'Bakers Choice',
    price: 3.49,
    rating: 4.3,
    reviewCount: 156,
    inventory: 89,
    description: 'Soft, split-top hot dog buns. Perfect size for standard frankfurters.',
    category: 'food',
    subcategory: 'bread',
    tags: ['hot-dog', 'buns', 'grilling', 'bbq'],
    canonicalType: 'hot_dog_buns',
    image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=400&h=400&fit=crop',
    unit: '8 pack',
  },
  {
    id: 'food-009',
    name: 'Flour Tortillas Large',
    brand: 'Casa Mexicana',
    price: 3.99,
    rating: 4.6,
    reviewCount: 387,
    inventory: 92,
    description: 'Soft, pliable flour tortillas perfect for burritos, quesadillas, and wraps.',
    category: 'food',
    subcategory: 'bread',
    tags: ['mexican', 'tortilla', 'wrap', 'burrito'],
    canonicalType: 'tortillas',
    image: 'https://images.unsplash.com/photo-1628191139360-4083564d03fd?w=400&h=400&fit=crop',
    unit: '10 pack',
  },
  {
    id: 'food-010',
    name: 'Seasoned Taco Beef',
    brand: 'Casa Mexicana',
    price: 8.99,
    rating: 4.5,
    reviewCount: 243,
    inventory: 34,
    description: 'Pre-seasoned ground beef with authentic Mexican spices. Ready to heat and serve.',
    category: 'food',
    subcategory: 'meat',
    tags: ['mexican', 'taco', 'beef', 'seasoned'],
    canonicalType: 'taco_meat',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=400&fit=crop',
    unit: '400g',
  },
  {
    id: 'food-011',
    name: 'Organic Free-Range Eggs',
    brand: 'Happy Hens',
    price: 6.49,
    rating: 4.8,
    reviewCount: 654,
    inventory: 45,
    description: 'Large brown eggs from pasture-raised hens. Rich, golden yolks.',
    category: 'food',
    subcategory: 'dairy',
    tags: ['eggs', 'organic', 'breakfast', 'protein'],
    canonicalType: 'eggs',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop',
    unit: '12 pack',
  },
  {
    id: 'food-012',
    name: 'Whole Milk',
    brand: 'Green Valley',
    price: 4.29,
    rating: 4.6,
    reviewCount: 432,
    inventory: 78,
    description: 'Fresh whole milk from grass-fed cows. Creamy and delicious.',
    category: 'food',
    subcategory: 'dairy',
    tags: ['milk', 'dairy', 'breakfast', 'calcium'],
    canonicalType: 'milk',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop',
    unit: '1 gallon',
  },
  {
    id: 'food-013',
    name: 'Colombian Single Origin Coffee',
    brand: 'Mountain Roast',
    price: 14.99,
    rating: 4.9,
    reviewCount: 876,
    inventory: 56,
    description: 'Medium roast Arabica beans with notes of chocolate and citrus. Fair trade certified.',
    category: 'food',
    subcategory: 'beverages',
    tags: ['coffee', 'colombian', 'breakfast', 'fair-trade'],
    canonicalType: 'coffee',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
    unit: '340g',
  },
  {
    id: 'food-014',
    name: 'Mixed Baby Greens Salad',
    brand: 'Fresh Farms',
    price: 4.99,
    rating: 4.4,
    reviewCount: 234,
    inventory: 32,
    description: 'Triple-washed mixed greens including arugula, spinach, and butter lettuce.',
    category: 'food',
    subcategory: 'vegetables',
    tags: ['salad', 'greens', 'healthy', 'organic'],
    canonicalType: 'salad_greens',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=400&fit=crop',
    unit: '150g',
  },
  {
    id: 'food-015',
    name: 'Vanilla Birthday Cake Mix',
    brand: 'Sweet Home',
    price: 3.99,
    rating: 4.5,
    reviewCount: 543,
    inventory: 67,
    description: 'Classic vanilla cake mix. Just add eggs, oil, and water for perfect results.',
    category: 'food',
    subcategory: 'baking',
    tags: ['cake', 'baking', 'birthday', 'vanilla'],
    canonicalType: 'cake_mix',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop',
    unit: '432g',
  },
  {
    id: 'food-016',
    name: 'Birthday Candles Assorted',
    brand: 'Party Time',
    price: 2.99,
    rating: 4.3,
    reviewCount: 187,
    inventory: 124,
    description: 'Colorful birthday candles in assorted colors. Includes candle holders.',
    category: 'food',
    subcategory: 'party',
    tags: ['candles', 'birthday', 'party', 'celebration'],
    canonicalType: 'birthday_candles',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&h=400&fit=crop',
    unit: '24 pack',
  },
  {
    id: 'food-017',
    name: 'Organic Avocados',
    brand: 'California Farms',
    price: 5.99,
    originalPrice: 7.49,
    discount: 20,
    rating: 4.6,
    reviewCount: 432,
    inventory: 28,
    description: 'Ripe Hass avocados, perfect for guacamole or toast. Ready to eat.',
    category: 'food',
    subcategory: 'vegetables',
    tags: ['avocado', 'organic', 'healthy', 'mexican'],
    canonicalType: 'avocado',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop',
    unit: '4 pack',
  },
  {
    id: 'food-018',
    name: 'Sea Salt Kettle Chips',
    brand: 'Crunch Time',
    price: 3.49,
    rating: 4.5,
    reviewCount: 876,
    inventory: 98,
    description: 'Thick-cut kettle chips with sea salt. Extra crunchy texture.',
    category: 'food',
    subcategory: 'snacks',
    tags: ['chips', 'snacks', 'salty', 'party'],
    canonicalType: 'chips',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop',
    unit: '200g',
  },
  {
    id: 'food-019',
    name: 'Greek Yogurt Plain',
    brand: 'Olympus',
    price: 5.99,
    rating: 4.7,
    reviewCount: 543,
    inventory: 45,
    description: 'Thick, creamy Greek yogurt with 15g protein per serving. No added sugar.',
    category: 'food',
    subcategory: 'dairy',
    tags: ['yogurt', 'greek', 'protein', 'breakfast'],
    canonicalType: 'yogurt',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop',
    unit: '500g',
  },
  {
    id: 'food-020',
    name: 'Fresh Atlantic Salmon',
    brand: 'Ocean Prime',
    price: 18.99,
    originalPrice: 22.99,
    discount: 17,
    rating: 4.8,
    reviewCount: 321,
    inventory: 18,
    description: 'Wild-caught Atlantic salmon fillet. Rich in omega-3 fatty acids.',
    category: 'food',
    subcategory: 'seafood',
    tags: ['salmon', 'fish', 'omega-3', 'healthy', 'dinner'],
    canonicalType: 'salmon',
    image: 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=400&h=400&fit=crop',
    unit: '400g',
  },
];

// =============================================================================
// GROCERY CATEGORY (18 products)
// =============================================================================

const groceryProducts: Product[] = [
  {
    id: 'grocery-001',
    name: 'Basmati Rice Premium',
    brand: 'Royal Harvest',
    price: 8.99,
    rating: 4.7,
    reviewCount: 654,
    inventory: 89,
    description: 'Aged basmati rice with extra-long grains. Aromatic and fluffy when cooked.',
    category: 'grocery',
    subcategory: 'grains',
    tags: ['rice', 'basmati', 'indian', 'staple'],
    canonicalType: 'rice',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
    unit: '2kg',
  },
  {
    id: 'grocery-002',
    name: 'All-Purpose Flour',
    brand: 'Gold Medal',
    price: 4.49,
    rating: 4.6,
    reviewCount: 432,
    inventory: 123,
    description: 'Unbleached all-purpose flour for baking, cooking, and breading.',
    category: 'grocery',
    subcategory: 'baking',
    tags: ['flour', 'baking', 'staple'],
    canonicalType: 'flour',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=400&fit=crop',
    unit: '2.26kg',
  },
  {
    id: 'grocery-003',
    name: 'Pure Cane Sugar',
    brand: 'Domino',
    price: 3.99,
    rating: 4.5,
    reviewCount: 287,
    inventory: 156,
    description: 'Fine granulated pure cane sugar for baking and sweetening.',
    category: 'grocery',
    subcategory: 'baking',
    tags: ['sugar', 'baking', 'staple'],
    canonicalType: 'sugar',
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop',
    unit: '1.8kg',
  },
  {
    id: 'grocery-004',
    name: 'Extra Virgin Olive Oil',
    brand: 'Terra Verde',
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    rating: 4.8,
    reviewCount: 876,
    inventory: 67,
    description: 'Cold-pressed extra virgin olive oil from Mediterranean olives. Perfect for cooking and dressings.',
    category: 'grocery',
    subcategory: 'oils',
    tags: ['olive-oil', 'cooking', 'mediterranean', 'healthy'],
    canonicalType: 'olive_oil',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
    unit: '750ml',
  },
  {
    id: 'grocery-005',
    name: 'Multi-Surface Cleaner',
    brand: 'CleanPro',
    price: 4.99,
    rating: 4.4,
    reviewCount: 321,
    inventory: 89,
    description: 'All-purpose cleaning spray for kitchen, bathroom, and surfaces. Lemon fresh scent.',
    category: 'grocery',
    subcategory: 'cleaning',
    tags: ['cleaner', 'cleaning', 'household', 'lemon'],
    canonicalType: 'surface_cleaner',
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=400&h=400&fit=crop',
    unit: '750ml',
  },
  {
    id: 'grocery-006',
    name: 'Dish Soap Liquid',
    brand: 'CleanPro',
    price: 3.49,
    rating: 4.5,
    reviewCount: 456,
    inventory: 134,
    description: 'Concentrated dish soap that cuts through grease. Gentle on hands.',
    category: 'grocery',
    subcategory: 'cleaning',
    tags: ['dish-soap', 'cleaning', 'kitchen'],
    canonicalType: 'dish_soap',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=400&h=400&fit=crop',
    unit: '500ml',
  },
  {
    id: 'grocery-007',
    name: 'Laundry Detergent Pods',
    brand: 'Fresh & Clean',
    price: 18.99,
    originalPrice: 22.99,
    discount: 17,
    rating: 4.7,
    reviewCount: 765,
    inventory: 45,
    description: '3-in-1 laundry pods with detergent, stain remover, and brightener.',
    category: 'grocery',
    subcategory: 'cleaning',
    tags: ['laundry', 'detergent', 'cleaning', 'pods'],
    canonicalType: 'laundry_detergent',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&h=400&fit=crop',
    unit: '42 pods',
  },
  {
    id: 'grocery-008',
    name: 'Paper Towels 6-Pack',
    brand: 'Bounty',
    price: 12.99,
    rating: 4.6,
    reviewCount: 543,
    inventory: 78,
    description: 'Super absorbent paper towels. Select-a-size sheets.',
    category: 'grocery',
    subcategory: 'paper',
    tags: ['paper-towels', 'cleaning', 'household'],
    canonicalType: 'paper_towels',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
    unit: '6 rolls',
  },
  {
    id: 'grocery-009',
    name: 'Toilet Paper 12-Pack',
    brand: 'Charmin',
    price: 14.99,
    rating: 4.7,
    reviewCount: 876,
    inventory: 67,
    description: 'Ultra soft toilet paper. Septic-safe and clog-free.',
    category: 'grocery',
    subcategory: 'paper',
    tags: ['toilet-paper', 'bathroom', 'household'],
    canonicalType: 'toilet_paper',
    image: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400&h=400&fit=crop',
    unit: '12 mega rolls',
  },
  {
    id: 'grocery-010',
    name: 'Trash Bags 50-Count',
    brand: 'Hefty',
    price: 11.99,
    rating: 4.5,
    reviewCount: 432,
    inventory: 89,
    description: 'Strong 13-gallon trash bags with drawstring closure. Odor block technology.',
    category: 'grocery',
    subcategory: 'cleaning',
    tags: ['trash-bags', 'cleaning', 'household'],
    canonicalType: 'trash_bags',
    image: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=400&h=400&fit=crop',
    unit: '50 bags',
  },
  {
    id: 'grocery-011',
    name: 'Organic Honey',
    brand: 'Nature Sweet',
    price: 9.99,
    rating: 4.8,
    reviewCount: 321,
    inventory: 45,
    description: 'Raw, unfiltered organic honey from wildflower blossoms.',
    category: 'grocery',
    subcategory: 'sweeteners',
    tags: ['honey', 'organic', 'natural', 'sweetener'],
    canonicalType: 'honey',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop',
    unit: '500g',
  },
  {
    id: 'grocery-012',
    name: 'Black Peppercorns',
    brand: 'Spice World',
    price: 6.99,
    rating: 4.6,
    reviewCount: 234,
    inventory: 78,
    description: 'Whole black peppercorns for grinding. Strong, aromatic flavor.',
    category: 'grocery',
    subcategory: 'spices',
    tags: ['pepper', 'spices', 'cooking'],
    canonicalType: 'pepper',
    image: 'https://images.unsplash.com/photo-1599909533681-74084861b19f?w=400&h=400&fit=crop',
    unit: '100g',
  },
  {
    id: 'grocery-013',
    name: 'Sea Salt Flakes',
    brand: 'Maldon',
    price: 7.99,
    rating: 4.9,
    reviewCount: 543,
    inventory: 56,
    description: 'Hand-harvested sea salt flakes. Perfect finishing salt.',
    category: 'grocery',
    subcategory: 'spices',
    tags: ['salt', 'sea-salt', 'finishing', 'gourmet'],
    canonicalType: 'salt',
    image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=400&h=400&fit=crop',
    unit: '250g',
  },
  {
    id: 'grocery-014',
    name: 'Soy Sauce',
    brand: 'Kikkoman',
    price: 4.99,
    rating: 4.7,
    reviewCount: 876,
    inventory: 98,
    description: 'Naturally brewed soy sauce with rich umami flavor.',
    category: 'grocery',
    subcategory: 'condiments',
    tags: ['soy-sauce', 'asian', 'condiment'],
    canonicalType: 'soy_sauce',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=400&h=400&fit=crop',
    unit: '500ml',
  },
  {
    id: 'grocery-015',
    name: 'Canned Diced Tomatoes',
    brand: 'Mutti',
    price: 2.99,
    rating: 4.6,
    reviewCount: 432,
    inventory: 145,
    description: 'Italian diced tomatoes in their own juice. Perfect for sauces and stews.',
    category: 'grocery',
    subcategory: 'canned',
    tags: ['tomatoes', 'canned', 'italian', 'cooking'],
    canonicalType: 'canned_tomatoes',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=400&fit=crop',
    unit: '400g',
  },
  {
    id: 'grocery-016',
    name: 'Chickpeas Canned',
    brand: 'Goya',
    price: 1.99,
    rating: 4.5,
    reviewCount: 321,
    inventory: 167,
    description: 'Ready-to-use chickpeas. Great for salads, hummus, and curries.',
    category: 'grocery',
    subcategory: 'canned',
    tags: ['chickpeas', 'canned', 'legumes', 'protein'],
    canonicalType: 'chickpeas',
    image: 'https://images.unsplash.com/photo-1515543904323-87f55f147e0d?w=400&h=400&fit=crop',
    unit: '400g',
  },
  {
    id: 'grocery-017',
    name: 'Coconut Milk',
    brand: 'Thai Kitchen',
    price: 3.49,
    rating: 4.6,
    reviewCount: 287,
    inventory: 89,
    description: 'Full-fat coconut milk for curries, soups, and desserts.',
    category: 'grocery',
    subcategory: 'canned',
    tags: ['coconut', 'milk', 'asian', 'cooking'],
    canonicalType: 'coconut_milk',
    image: 'https://images.unsplash.com/photo-1550411294-875e92759eb5?w=400&h=400&fit=crop',
    unit: '400ml',
  },
  {
    id: 'grocery-018',
    name: 'Peanut Butter Creamy',
    brand: "Skippy",
    price: 5.49,
    rating: 4.5,
    reviewCount: 654,
    inventory: 78,
    description: 'Smooth, creamy peanut butter made with roasted peanuts.',
    category: 'grocery',
    subcategory: 'spreads',
    tags: ['peanut-butter', 'spread', 'breakfast', 'protein'],
    canonicalType: 'peanut_butter',
    image: 'https://images.unsplash.com/photo-1600189536574-8d8eef0d9bea?w=400&h=400&fit=crop',
    unit: '462g',
  },
];

// =============================================================================
// PHARMACY CATEGORY (16 products)
// =============================================================================

const pharmacyProducts: Product[] = [
  {
    id: 'pharmacy-001',
    name: 'Ibuprofen 200mg',
    brand: 'Advil',
    price: 9.99,
    rating: 4.7,
    reviewCount: 1243,
    inventory: 89,
    description: 'Fast-acting pain relief for headaches, muscle aches, and fever.',
    category: 'pharmacy',
    subcategory: 'pain-relief',
    tags: ['pain-relief', 'headache', 'fever', 'anti-inflammatory'],
    canonicalType: 'pain_reliever',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    unit: '100 tablets',
    warnings: 'Do not exceed recommended dose. Consult doctor if symptoms persist.',
  },
  {
    id: 'pharmacy-002',
    name: 'Acetaminophen 500mg',
    brand: 'Tylenol',
    price: 8.99,
    rating: 4.6,
    reviewCount: 987,
    inventory: 123,
    description: 'Effective pain relief and fever reducer. Gentle on stomach.',
    category: 'pharmacy',
    subcategory: 'pain-relief',
    tags: ['pain-relief', 'fever', 'headache'],
    canonicalType: 'pain_reliever',
    image: 'https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=400&h=400&fit=crop',
    unit: '100 tablets',
    warnings: 'Do not take with alcohol. Follow dosage instructions.',
  },
  {
    id: 'pharmacy-003',
    name: 'Vitamin D3 2000 IU',
    brand: 'Nature Made',
    price: 12.99,
    rating: 4.8,
    reviewCount: 2134,
    inventory: 67,
    description: 'Essential vitamin D3 for bone health and immune support.',
    category: 'pharmacy',
    subcategory: 'vitamins',
    tags: ['vitamin-d', 'vitamins', 'immune', 'bone-health'],
    canonicalType: 'vitamin_d',
    image: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
    unit: '200 softgels',
  },
  {
    id: 'pharmacy-004',
    name: 'Multivitamin Complete',
    brand: 'Centrum',
    price: 18.99,
    originalPrice: 23.99,
    discount: 21,
    rating: 4.7,
    reviewCount: 1567,
    inventory: 45,
    description: 'Complete daily multivitamin with essential nutrients for overall health.',
    category: 'pharmacy',
    subcategory: 'vitamins',
    tags: ['multivitamin', 'vitamins', 'daily', 'health'],
    canonicalType: 'multivitamin',
    image: 'https://images.unsplash.com/photo-1559757175-7b21e7afb8f3?w=400&h=400&fit=crop',
    unit: '150 tablets',
  },
  {
    id: 'pharmacy-005',
    name: 'First Aid Kit Complete',
    brand: 'Johnson & Johnson',
    price: 24.99,
    rating: 4.6,
    reviewCount: 876,
    inventory: 34,
    description: 'Comprehensive first aid kit with bandages, antiseptic, and essential supplies.',
    category: 'pharmacy',
    subcategory: 'first-aid',
    tags: ['first-aid', 'bandages', 'emergency', 'safety'],
    canonicalType: 'first_aid_kit',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&h=400&fit=crop',
    unit: '200 pieces',
  },
  {
    id: 'pharmacy-006',
    name: 'Adhesive Bandages',
    brand: 'Band-Aid',
    price: 5.99,
    rating: 4.5,
    reviewCount: 1234,
    inventory: 156,
    description: 'Flexible fabric bandages that stay on. Assorted sizes.',
    category: 'pharmacy',
    subcategory: 'first-aid',
    tags: ['bandages', 'first-aid', 'cuts', 'wounds'],
    canonicalType: 'bandages',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=400&h=400&fit=crop',
    unit: '100 bandages',
  },
  {
    id: 'pharmacy-007',
    name: 'Hand Sanitizer Gel',
    brand: 'Purell',
    price: 6.99,
    rating: 4.7,
    reviewCount: 2345,
    inventory: 189,
    description: 'Kills 99.99% of germs. Moisturizing formula with aloe.',
    category: 'pharmacy',
    subcategory: 'personal-care',
    tags: ['hand-sanitizer', 'hygiene', 'antibacterial'],
    canonicalType: 'hand_sanitizer',
    image: 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=400&h=400&fit=crop',
    unit: '354ml',
  },
  {
    id: 'pharmacy-008',
    name: 'Allergy Relief 24hr',
    brand: 'Claritin',
    price: 22.99,
    originalPrice: 27.99,
    discount: 18,
    rating: 4.6,
    reviewCount: 1876,
    inventory: 56,
    description: 'Non-drowsy 24-hour allergy relief for indoor and outdoor allergies.',
    category: 'pharmacy',
    subcategory: 'allergy',
    tags: ['allergy', 'antihistamine', 'non-drowsy'],
    canonicalType: 'allergy_medicine',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
    unit: '30 tablets',
  },
  {
    id: 'pharmacy-009',
    name: 'Omega-3 Fish Oil',
    brand: 'Nordic Naturals',
    price: 29.99,
    rating: 4.8,
    reviewCount: 1432,
    inventory: 45,
    description: 'High-potency omega-3 fish oil for heart and brain health.',
    category: 'pharmacy',
    subcategory: 'vitamins',
    tags: ['omega-3', 'fish-oil', 'heart-health', 'supplements'],
    canonicalType: 'fish_oil',
    image: 'https://images.unsplash.com/photo-1608138278545-366680accc66?w=400&h=400&fit=crop',
    unit: '120 softgels',
  },
  {
    id: 'pharmacy-010',
    name: 'Probiotic Daily',
    brand: 'Culturelle',
    price: 24.99,
    rating: 4.7,
    reviewCount: 987,
    inventory: 67,
    description: 'Daily probiotic for digestive and immune health.',
    category: 'pharmacy',
    subcategory: 'vitamins',
    tags: ['probiotic', 'digestive', 'gut-health', 'immune'],
    canonicalType: 'probiotic',
    image: 'https://images.unsplash.com/photo-1618939291225-c52cffd6b285?w=400&h=400&fit=crop',
    unit: '30 capsules',
  },
  {
    id: 'pharmacy-011',
    name: 'Sunscreen SPF 50',
    brand: 'Neutrogena',
    price: 14.99,
    rating: 4.6,
    reviewCount: 2134,
    inventory: 78,
    description: 'Broad spectrum UVA/UVB protection. Water resistant 80 minutes.',
    category: 'pharmacy',
    subcategory: 'personal-care',
    tags: ['sunscreen', 'sun-protection', 'skincare', 'spf'],
    canonicalType: 'sunscreen',
    image: 'https://images.unsplash.com/photo-1556227834-09f1de7a7d14?w=400&h=400&fit=crop',
    unit: '147ml',
  },
  {
    id: 'pharmacy-012',
    name: 'Lip Balm SPF 15',
    brand: "Burt's Bees",
    price: 3.99,
    rating: 4.5,
    reviewCount: 1654,
    inventory: 234,
    description: 'Natural beeswax lip balm with sun protection. Moisturizing formula.',
    category: 'pharmacy',
    subcategory: 'personal-care',
    tags: ['lip-balm', 'moisturizing', 'natural', 'spf'],
    canonicalType: 'lip_balm',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop',
    unit: '4.25g',
  },
  {
    id: 'pharmacy-013',
    name: 'Melatonin 5mg',
    brand: 'Natrol',
    price: 11.99,
    rating: 4.6,
    reviewCount: 1876,
    inventory: 89,
    description: 'Natural sleep aid for occasional sleeplessness. Non-habit forming.',
    category: 'pharmacy',
    subcategory: 'sleep',
    tags: ['melatonin', 'sleep', 'natural', 'supplement'],
    canonicalType: 'melatonin',
    image: 'https://images.unsplash.com/photo-1550572017-26b5655f9dd8?w=400&h=400&fit=crop',
    unit: '60 tablets',
  },
  {
    id: 'pharmacy-014',
    name: 'Cough Syrup DM',
    brand: 'Robitussin',
    price: 10.99,
    rating: 4.4,
    reviewCount: 765,
    inventory: 67,
    description: 'Relieves cough and chest congestion for up to 8 hours.',
    category: 'pharmacy',
    subcategory: 'cold-flu',
    tags: ['cough', 'cold', 'congestion', 'relief'],
    canonicalType: 'cough_medicine',
    image: 'https://images.unsplash.com/photo-1587854680352-936b22b91030?w=400&h=400&fit=crop',
    unit: '236ml',
    warnings: 'Do not exceed recommended dosage.',
  },
  {
    id: 'pharmacy-015',
    name: 'Digital Thermometer',
    brand: 'Braun',
    price: 19.99,
    rating: 4.7,
    reviewCount: 1234,
    inventory: 45,
    description: 'Fast, accurate digital thermometer with fever indicator.',
    category: 'pharmacy',
    subcategory: 'first-aid',
    tags: ['thermometer', 'digital', 'fever', 'health'],
    canonicalType: 'thermometer',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    unit: '1 unit',
  },
  {
    id: 'pharmacy-016',
    name: 'Vitamin C 1000mg',
    brand: 'Emergen-C',
    price: 14.99,
    rating: 4.6,
    reviewCount: 2345,
    inventory: 98,
    description: 'High-potency vitamin C for immune support. Citrus flavor.',
    category: 'pharmacy',
    subcategory: 'vitamins',
    tags: ['vitamin-c', 'immune', 'antioxidant', 'supplement'],
    canonicalType: 'vitamin_c',
    image: 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=400&h=400&fit=crop',
    unit: '30 packets',
  },
];

// =============================================================================
// HOME CATEGORY (16 products)
// =============================================================================

const homeProducts: Product[] = [
  {
    id: 'home-001',
    name: 'Non-Stick Frying Pan',
    brand: 'T-fal',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    rating: 4.6,
    reviewCount: 2345,
    inventory: 45,
    description: '12-inch non-stick frying pan with heat indicator. PFOA-free coating.',
    category: 'home',
    subcategory: 'kitchen',
    tags: ['cookware', 'frying-pan', 'non-stick', 'cooking'],
    canonicalType: 'frying_pan',
    image: 'https://images.unsplash.com/photo-1592156328757-370f1fdb3b51?w=400&h=400&fit=crop',
    unit: '1 pan',
  },
  {
    id: 'home-002',
    name: "Chef's Knife 8-inch",
    brand: 'Victorinox',
    price: 34.99,
    rating: 4.8,
    reviewCount: 3456,
    inventory: 34,
    description: 'Professional-grade chef knife with high-carbon stainless steel blade.',
    category: 'home',
    subcategory: 'kitchen',
    tags: ['knife', 'chef', 'kitchen', 'cutting'],
    canonicalType: 'chef_knife',
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&h=400&fit=crop',
    unit: '1 knife',
  },
  {
    id: 'home-003',
    name: 'Cutting Board Set',
    brand: 'OXO',
    price: 24.99,
    rating: 4.5,
    reviewCount: 1234,
    inventory: 56,
    description: 'Set of 3 color-coded cutting boards. Dishwasher safe, BPA-free.',
    category: 'home',
    subcategory: 'kitchen',
    tags: ['cutting-board', 'kitchen', 'food-prep'],
    canonicalType: 'cutting_board',
    image: 'https://images.unsplash.com/photo-1594666757003-3ee20de41568?w=400&h=400&fit=crop',
    unit: '3 boards',
  },
  {
    id: 'home-004',
    name: 'Food Storage Containers',
    brand: 'Rubbermaid',
    price: 19.99,
    rating: 4.6,
    reviewCount: 2134,
    inventory: 78,
    description: '10-piece set of airtight food storage containers. Microwave and dishwasher safe.',
    category: 'home',
    subcategory: 'storage',
    tags: ['storage', 'containers', 'food-storage', 'kitchen'],
    canonicalType: 'food_containers',
    image: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=400&h=400&fit=crop',
    unit: '10 piece set',
  },
  {
    id: 'home-005',
    name: 'Glass Mixing Bowls',
    brand: 'Pyrex',
    price: 29.99,
    rating: 4.7,
    reviewCount: 1876,
    inventory: 45,
    description: '4-piece nesting glass mixing bowl set. Microwave and oven safe.',
    category: 'home',
    subcategory: 'kitchen',
    tags: ['mixing-bowls', 'glass', 'baking', 'kitchen'],
    canonicalType: 'mixing_bowls',
    image: 'https://images.unsplash.com/photo-1591261731869-0d1c4e32e7f4?w=400&h=400&fit=crop',
    unit: '4 bowls',
  },
  {
    id: 'home-006',
    name: 'Stainless Steel Pot Set',
    brand: 'Cuisinart',
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    rating: 4.8,
    reviewCount: 987,
    inventory: 23,
    description: '10-piece stainless steel cookware set. Induction compatible.',
    category: 'home',
    subcategory: 'kitchen',
    tags: ['cookware', 'pots', 'stainless-steel', 'cooking'],
    canonicalType: 'pot_set',
    image: 'https://images.unsplash.com/photo-1584284087901-6f1c00a93e95?w=400&h=400&fit=crop',
    unit: '10 piece set',
  },
  {
    id: 'home-007',
    name: 'Silicone Utensil Set',
    brand: 'KitchenAid',
    price: 34.99,
    rating: 4.6,
    reviewCount: 1543,
    inventory: 67,
    description: '15-piece heat-resistant silicone cooking utensil set.',
    category: 'home',
    subcategory: 'kitchen',
    tags: ['utensils', 'silicone', 'cooking', 'kitchen'],
    canonicalType: 'utensil_set',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=400&h=400&fit=crop',
    unit: '15 pieces',
  },
  {
    id: 'home-008',
    name: 'Closet Organizer System',
    brand: 'ClosetMaid',
    price: 89.99,
    rating: 4.5,
    reviewCount: 876,
    inventory: 34,
    description: 'Modular closet organization system with shelves and hanging rods.',
    category: 'home',
    subcategory: 'storage',
    tags: ['closet', 'organizer', 'storage', 'bedroom'],
    canonicalType: 'closet_organizer',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    unit: '1 system',
  },
  {
    id: 'home-009',
    name: 'Desk Organizer',
    brand: 'SimpleHouseware',
    price: 19.99,
    rating: 4.4,
    reviewCount: 2134,
    inventory: 89,
    description: 'Mesh desk organizer with file holder and pencil cup.',
    category: 'home',
    subcategory: 'storage',
    tags: ['desk', 'organizer', 'office', 'storage'],
    canonicalType: 'desk_organizer',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop',
    unit: '1 set',
  },
  {
    id: 'home-010',
    name: 'Bath Towel Set',
    brand: 'Utopia Towels',
    price: 39.99,
    rating: 4.6,
    reviewCount: 3456,
    inventory: 56,
    description: '8-piece cotton bath towel set. Soft, absorbent, quick-drying.',
    category: 'home',
    subcategory: 'bathroom',
    tags: ['towels', 'bath', 'cotton', 'bathroom'],
    canonicalType: 'towels',
    image: 'https://images.unsplash.com/photo-1600693577273-eb8307b28a3e?w=400&h=400&fit=crop',
    unit: '8 towels',
  },
  {
    id: 'home-011',
    name: 'Shower Caddy',
    brand: 'SimpleHuman',
    price: 29.99,
    rating: 4.5,
    reviewCount: 1234,
    inventory: 78,
    description: 'Rust-proof stainless steel shower caddy with multiple compartments.',
    category: 'home',
    subcategory: 'bathroom',
    tags: ['shower', 'caddy', 'bathroom', 'storage'],
    canonicalType: 'shower_caddy',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=400&h=400&fit=crop',
    unit: '1 caddy',
  },
  {
    id: 'home-012',
    name: 'LED Desk Lamp',
    brand: 'TaoTronics',
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    rating: 4.7,
    reviewCount: 2876,
    inventory: 45,
    description: 'Adjustable LED desk lamp with USB charging port. 5 color modes.',
    category: 'home',
    subcategory: 'lighting',
    tags: ['lamp', 'led', 'desk', 'office', 'lighting'],
    canonicalType: 'desk_lamp',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop',
    unit: '1 lamp',
  },
  {
    id: 'home-013',
    name: 'Throw Blanket',
    brand: 'Bedsure',
    price: 24.99,
    rating: 4.6,
    reviewCount: 4567,
    inventory: 67,
    description: 'Soft fleece throw blanket. 50x60 inches. Machine washable.',
    category: 'home',
    subcategory: 'bedroom',
    tags: ['blanket', 'fleece', 'cozy', 'bedroom'],
    canonicalType: 'throw_blanket',
    image: 'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=400&h=400&fit=crop',
    unit: '1 blanket',
  },
  {
    id: 'home-014',
    name: 'Vacuum Cleaner Cordless',
    brand: 'Dyson',
    price: 399.99,
    originalPrice: 499.99,
    discount: 20,
    rating: 4.8,
    reviewCount: 5678,
    inventory: 18,
    description: 'Powerful cordless stick vacuum with up to 40 minutes runtime.',
    category: 'home',
    subcategory: 'cleaning',
    tags: ['vacuum', 'cordless', 'cleaning', 'appliance'],
    canonicalType: 'vacuum',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop',
    unit: '1 vacuum',
  },
  {
    id: 'home-015',
    name: 'Air Purifier',
    brand: 'Levoit',
    price: 89.99,
    rating: 4.6,
    reviewCount: 3456,
    inventory: 34,
    description: 'HEPA air purifier for rooms up to 300 sq ft. Removes allergens and odors.',
    category: 'home',
    subcategory: 'appliances',
    tags: ['air-purifier', 'hepa', 'allergens', 'health'],
    canonicalType: 'air_purifier',
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop',
    unit: '1 purifier',
  },
  {
    id: 'home-016',
    name: 'Robot Vacuum',
    brand: 'iRobot',
    price: 279.99,
    originalPrice: 349.99,
    discount: 20,
    rating: 4.7,
    reviewCount: 4321,
    inventory: 23,
    description: 'Smart robot vacuum with app control and automatic charging.',
    category: 'home',
    subcategory: 'cleaning',
    tags: ['robot-vacuum', 'smart', 'cleaning', 'automated'],
    canonicalType: 'robot_vacuum',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    unit: '1 vacuum',
  },
];

// =============================================================================
// ELECTRONICS CATEGORY (15 products)
// =============================================================================

const electronicsProducts: Product[] = [
  {
    id: 'electronics-001',
    name: 'Wireless Earbuds Pro',
    brand: 'Sony',
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.8,
    reviewCount: 8765,
    inventory: 45,
    description: 'True wireless earbuds with active noise cancellation and 24hr battery.',
    category: 'electronics',
    subcategory: 'audio',
    tags: ['earbuds', 'wireless', 'noise-cancelling', 'bluetooth'],
    canonicalType: 'wireless_earbuds',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
    unit: '1 pair',
  },
  {
    id: 'electronics-002',
    name: 'Over-Ear Headphones',
    brand: 'Bose',
    price: 329.99,
    rating: 4.9,
    reviewCount: 5432,
    inventory: 34,
    description: 'Premium wireless headphones with world-class noise cancellation.',
    category: 'electronics',
    subcategory: 'audio',
    tags: ['headphones', 'wireless', 'noise-cancelling', 'premium'],
    canonicalType: 'headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    unit: '1 pair',
  },
  {
    id: 'electronics-003',
    name: 'Portable Bluetooth Speaker',
    brand: 'JBL',
    price: 129.99,
    originalPrice: 149.99,
    discount: 13,
    rating: 4.7,
    reviewCount: 6543,
    inventory: 67,
    description: 'Waterproof portable speaker with 20hr battery. Powerful bass.',
    category: 'electronics',
    subcategory: 'audio',
    tags: ['speaker', 'bluetooth', 'portable', 'waterproof'],
    canonicalType: 'bluetooth_speaker',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    unit: '1 speaker',
  },
  {
    id: 'electronics-004',
    name: '27" 4K Monitor',
    brand: 'Dell',
    price: 349.99,
    rating: 4.7,
    reviewCount: 3456,
    inventory: 28,
    description: '27-inch 4K UHD monitor with USB-C connectivity. 99% sRGB.',
    category: 'electronics',
    subcategory: 'monitors',
    tags: ['monitor', '4k', 'usb-c', 'office'],
    canonicalType: 'monitor',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop',
    unit: '1 monitor',
  },
  {
    id: 'electronics-005',
    name: '34" Ultrawide Gaming Monitor',
    brand: 'LG',
    price: 499.99,
    originalPrice: 599.99,
    discount: 17,
    rating: 4.8,
    reviewCount: 2345,
    inventory: 18,
    description: '34-inch curved ultrawide gaming monitor. 144Hz, 1ms response.',
    category: 'electronics',
    subcategory: 'monitors',
    tags: ['monitor', 'gaming', 'ultrawide', 'curved'],
    canonicalType: 'gaming_monitor',
    image: 'https://images.unsplash.com/photo-1616763355603-9755a640a287?w=400&h=400&fit=crop',
    unit: '1 monitor',
  },
  {
    id: 'electronics-006',
    name: 'Mechanical Keyboard RGB',
    brand: 'Logitech',
    price: 129.99,
    rating: 4.6,
    reviewCount: 4567,
    inventory: 56,
    description: 'RGB mechanical gaming keyboard with tactile switches.',
    category: 'electronics',
    subcategory: 'peripherals',
    tags: ['keyboard', 'mechanical', 'gaming', 'rgb'],
    canonicalType: 'keyboard',
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=400&fit=crop',
    unit: '1 keyboard',
  },
  {
    id: 'electronics-007',
    name: 'Wireless Gaming Mouse',
    brand: 'Razer',
    price: 79.99,
    rating: 4.7,
    reviewCount: 3456,
    inventory: 78,
    description: 'Lightweight wireless gaming mouse with 25K DPI optical sensor.',
    category: 'electronics',
    subcategory: 'peripherals',
    tags: ['mouse', 'gaming', 'wireless', 'precision'],
    canonicalType: 'gaming_mouse',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    unit: '1 mouse',
  },
  {
    id: 'electronics-008',
    name: 'Webcam 4K',
    brand: 'Logitech',
    price: 169.99,
    rating: 4.6,
    reviewCount: 2134,
    inventory: 45,
    description: '4K webcam with auto-focus and noise-cancelling mic.',
    category: 'electronics',
    subcategory: 'peripherals',
    tags: ['webcam', '4k', 'streaming', 'video'],
    canonicalType: 'webcam',
    image: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&h=400&fit=crop',
    unit: '1 webcam',
  },
  {
    id: 'electronics-009',
    name: 'USB-C Hub 10-in-1',
    brand: 'Anker',
    price: 59.99,
    rating: 4.5,
    reviewCount: 5678,
    inventory: 89,
    description: '10-in-1 USB-C hub with HDMI, USB-A, SD card, and ethernet.',
    category: 'electronics',
    subcategory: 'accessories',
    tags: ['usb-c', 'hub', 'laptop', 'connectivity'],
    canonicalType: 'usb_hub',
    image: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop',
    unit: '1 hub',
  },
  {
    id: 'electronics-010',
    name: 'Laptop Stand Adjustable',
    brand: 'Rain Design',
    price: 49.99,
    rating: 4.7,
    reviewCount: 3210,
    inventory: 67,
    description: 'Aluminum laptop stand with adjustable height. Improves ergonomics.',
    category: 'electronics',
    subcategory: 'accessories',
    tags: ['laptop-stand', 'ergonomic', 'aluminum', 'office'],
    canonicalType: 'laptop_stand',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    unit: '1 stand',
  },
  {
    id: 'electronics-011',
    name: 'Power Bank 20000mAh',
    brand: 'Anker',
    price: 49.99,
    rating: 4.8,
    reviewCount: 8765,
    inventory: 123,
    description: 'High-capacity power bank with fast charging. Charges 4 devices.',
    category: 'electronics',
    subcategory: 'accessories',
    tags: ['power-bank', 'charging', 'portable', 'travel'],
    canonicalType: 'power_bank',
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop',
    unit: '1 power bank',
  },
  {
    id: 'electronics-012',
    name: 'Smart Watch',
    brand: 'Apple',
    price: 399.99,
    rating: 4.9,
    reviewCount: 12345,
    inventory: 34,
    description: 'Advanced smartwatch with health monitoring and cellular.',
    category: 'electronics',
    subcategory: 'wearables',
    tags: ['smartwatch', 'fitness', 'health', 'wearable'],
    canonicalType: 'smartwatch',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop',
    unit: '1 watch',
  },
  {
    id: 'electronics-013',
    name: 'Tablet 10.9"',
    brand: 'Apple',
    price: 449.99,
    rating: 4.8,
    reviewCount: 7654,
    inventory: 28,
    description: '10.9-inch tablet with A14 Bionic chip. All-day battery life.',
    category: 'electronics',
    subcategory: 'tablets',
    tags: ['tablet', 'ipad', 'portable', 'entertainment'],
    canonicalType: 'tablet',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
    unit: '1 tablet',
  },
  {
    id: 'electronics-014',
    name: 'External SSD 1TB',
    brand: 'Samsung',
    price: 119.99,
    originalPrice: 149.99,
    discount: 20,
    rating: 4.8,
    reviewCount: 5432,
    inventory: 67,
    description: 'Portable SSD with 1050MB/s read speed. Shock resistant.',
    category: 'electronics',
    subcategory: 'storage',
    tags: ['ssd', 'storage', 'portable', 'backup'],
    canonicalType: 'external_ssd',
    image: 'https://images.unsplash.com/photo-1597838816882-4435b1977fbe?w=400&h=400&fit=crop',
    unit: '1TB',
  },
  {
    id: 'electronics-015',
    name: 'Wireless Charger Pad',
    brand: 'Belkin',
    price: 39.99,
    rating: 4.5,
    reviewCount: 3456,
    inventory: 98,
    description: '15W fast wireless charging pad. Compatible with all Qi devices.',
    category: 'electronics',
    subcategory: 'accessories',
    tags: ['wireless-charger', 'charging', 'qi', 'fast-charge'],
    canonicalType: 'wireless_charger',
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop',
    unit: '1 charger',
  },
];

// =============================================================================
// FASHION CATEGORY (15 products)
// =============================================================================

const fashionProducts: Product[] = [
  {
    id: 'fashion-001',
    name: 'Merino Wool Sweater',
    brand: 'Everlane',
    price: 98.00,
    rating: 4.7,
    reviewCount: 2345,
    inventory: 45,
    description: 'Lightweight merino wool crewneck sweater. Naturally temperature regulating.',
    category: 'fashion',
    subcategory: 'sweaters',
    tags: ['sweater', 'merino', 'wool', 'classic'],
    canonicalType: 'sweater',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL',
  },
  {
    id: 'fashion-002',
    name: 'Cashmere Cardigan',
    brand: 'Naadam',
    price: 175.00,
    originalPrice: 225.00,
    discount: 22,
    rating: 4.8,
    reviewCount: 1234,
    inventory: 28,
    description: 'Luxuriously soft 100% cashmere cardigan. Timeless style.',
    category: 'fashion',
    subcategory: 'sweaters',
    tags: ['cardigan', 'cashmere', 'luxury', 'classic'],
    canonicalType: 'cardigan',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL',
  },
  {
    id: 'fashion-003',
    name: 'Oxford Button-Down Shirt',
    brand: 'Brooks Brothers',
    price: 88.00,
    rating: 4.6,
    reviewCount: 3456,
    inventory: 67,
    description: 'Classic oxford cloth button-down shirt. Non-iron finish.',
    category: 'fashion',
    subcategory: 'shirts',
    tags: ['shirt', 'oxford', 'formal', 'classic'],
    canonicalType: 'dress_shirt',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL, XXL',
  },
  {
    id: 'fashion-004',
    name: 'Linen Summer Shirt',
    brand: 'J.Crew',
    price: 79.50,
    rating: 4.5,
    reviewCount: 1876,
    inventory: 56,
    description: 'Breathable linen shirt perfect for warm weather. Relaxed fit.',
    category: 'fashion',
    subcategory: 'shirts',
    tags: ['shirt', 'linen', 'summer', 'casual'],
    canonicalType: 'casual_shirt',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL',
  },
  {
    id: 'fashion-005',
    name: 'Leather Chelsea Boots',
    brand: 'Thursday Boot Co',
    price: 199.00,
    rating: 4.8,
    reviewCount: 4567,
    inventory: 34,
    description: 'Handcrafted leather Chelsea boots. Goodyear welt construction.',
    category: 'fashion',
    subcategory: 'shoes',
    tags: ['boots', 'chelsea', 'leather', 'classic'],
    canonicalType: 'boots',
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=400&h=400&fit=crop',
    unit: '7, 8, 9, 10, 11, 12',
  },
  {
    id: 'fashion-006',
    name: 'White Leather Sneakers',
    brand: 'Common Projects',
    price: 425.00,
    rating: 4.9,
    reviewCount: 2345,
    inventory: 23,
    description: 'Minimalist Italian leather sneakers. Gold serial number detail.',
    category: 'fashion',
    subcategory: 'shoes',
    tags: ['sneakers', 'leather', 'minimal', 'luxury'],
    canonicalType: 'sneakers',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
    unit: '7, 8, 9, 10, 11, 12',
  },
  {
    id: 'fashion-007',
    name: 'Running Shoes',
    brand: 'Nike',
    price: 130.00,
    originalPrice: 160.00,
    discount: 19,
    rating: 4.7,
    reviewCount: 8765,
    inventory: 89,
    description: 'Lightweight running shoes with responsive cushioning.',
    category: 'fashion',
    subcategory: 'shoes',
    tags: ['running', 'athletic', 'performance', 'sports'],
    canonicalType: 'running_shoes',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    unit: '7, 8, 9, 10, 11, 12',
  },
  {
    id: 'fashion-008',
    name: 'Waterproof Rain Jacket',
    brand: 'Patagonia',
    price: 179.00,
    rating: 4.8,
    reviewCount: 3456,
    inventory: 45,
    description: 'Lightweight, packable rain jacket. 100% recycled nylon.',
    category: 'fashion',
    subcategory: 'jackets',
    tags: ['jacket', 'rain', 'waterproof', 'outdoor'],
    canonicalType: 'rain_jacket',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL',
  },
  {
    id: 'fashion-009',
    name: 'Down Puffer Jacket',
    brand: 'North Face',
    price: 249.00,
    rating: 4.7,
    reviewCount: 5678,
    inventory: 34,
    description: '700-fill down insulated jacket. Packable and ultra-warm.',
    category: 'fashion',
    subcategory: 'jackets',
    tags: ['jacket', 'down', 'puffer', 'winter'],
    canonicalType: 'puffer_jacket',
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL, XXL',
  },
  {
    id: 'fashion-010',
    name: 'Denim Jacket Classic',
    brand: "Levi's",
    price: 98.00,
    rating: 4.6,
    reviewCount: 4321,
    inventory: 56,
    description: 'Iconic trucker jacket in medium wash denim. Timeless style.',
    category: 'fashion',
    subcategory: 'jackets',
    tags: ['jacket', 'denim', 'classic', 'casual'],
    canonicalType: 'denim_jacket',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&h=400&fit=crop',
    unit: 'S, M, L, XL',
  },
  {
    id: 'fashion-011',
    name: 'Slim Fit Chinos',
    brand: 'Bonobos',
    price: 98.00,
    rating: 4.6,
    reviewCount: 2876,
    inventory: 78,
    description: 'Stretch cotton chinos with perfect fit. Wrinkle-resistant.',
    category: 'fashion',
    subcategory: 'pants',
    tags: ['chinos', 'pants', 'slim', 'casual'],
    canonicalType: 'chinos',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop',
    unit: '30, 32, 34, 36, 38',
  },
  {
    id: 'fashion-012',
    name: 'Selvedge Denim Jeans',
    brand: 'A.P.C.',
    price: 220.00,
    rating: 4.8,
    reviewCount: 1654,
    inventory: 34,
    description: 'Japanese selvedge denim jeans. Raw, unwashed finish.',
    category: 'fashion',
    subcategory: 'pants',
    tags: ['jeans', 'denim', 'selvedge', 'premium'],
    canonicalType: 'jeans',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=400&fit=crop',
    unit: '30, 32, 34, 36',
  },
  {
    id: 'fashion-013',
    name: 'Leather Belt',
    brand: 'Allen Edmonds',
    price: 95.00,
    rating: 4.7,
    reviewCount: 2134,
    inventory: 67,
    description: 'Full-grain leather dress belt with classic buckle.',
    category: 'fashion',
    subcategory: 'accessories',
    tags: ['belt', 'leather', 'dress', 'classic'],
    canonicalType: 'belt',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
    unit: '32, 34, 36, 38, 40',
  },
  {
    id: 'fashion-014',
    name: 'Wool Beanie',
    brand: 'Carhartt',
    price: 24.99,
    rating: 4.5,
    reviewCount: 5432,
    inventory: 134,
    description: 'Ribbed knit acrylic beanie. Warm and comfortable.',
    category: 'fashion',
    subcategory: 'accessories',
    tags: ['beanie', 'hat', 'winter', 'casual'],
    canonicalType: 'beanie',
    image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=400&h=400&fit=crop',
    unit: 'One Size',
  },
  {
    id: 'fashion-015',
    name: 'Polarized Sunglasses',
    brand: 'Ray-Ban',
    price: 163.00,
    rating: 4.8,
    reviewCount: 7654,
    inventory: 45,
    description: 'Classic aviator sunglasses with polarized lenses.',
    category: 'fashion',
    subcategory: 'accessories',
    tags: ['sunglasses', 'polarized', 'aviator', 'classic'],
    canonicalType: 'sunglasses',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    unit: 'One Size',
  },
];

// =============================================================================
// EXPORT ALL PRODUCTS
// =============================================================================

export const allProducts: Product[] = [
  ...foodProducts,
  ...groceryProducts,
  ...pharmacyProducts,
  ...homeProducts,
  ...electronicsProducts,
  ...fashionProducts,
];

export const productsByCategory = {
  food: foodProducts,
  grocery: groceryProducts,
  pharmacy: pharmacyProducts,
  home: homeProducts,
  electronics: electronicsProducts,
  fashion: fashionProducts,
};

export const categories = [
  { id: 'food', name: 'Food', icon: 'utensils', count: foodProducts.length },
  { id: 'grocery', name: 'Grocery', icon: 'shopping-basket', count: groceryProducts.length },
  { id: 'pharmacy', name: 'Pharmacy', icon: 'pill', count: pharmacyProducts.length },
  { id: 'home', name: 'Home', icon: 'home', count: homeProducts.length },
  { id: 'electronics', name: 'Electronics', icon: 'laptop', count: electronicsProducts.length },
  { id: 'fashion', name: 'Fashion', icon: 'shirt', count: fashionProducts.length },
] as const;

// =============================================================================
// PRODUCT RELATIONSHIP PAIRS (for OPE testing)
// These are NOT hardcoded suggestions - just metadata for testing
// =============================================================================

export const relationshipPairs = [
  { primary: 'pasta', complement: 'pasta_sauce', category: 'food' },
  { primary: 'pasta', complement: 'cheese', category: 'food' },
  { primary: 'burger_patties', complement: 'burger_buns', category: 'food' },
  { primary: 'hot_dogs', complement: 'hot_dog_buns', category: 'food' },
  { primary: 'taco_meat', complement: 'tortillas', category: 'food' },
  { primary: 'cake_mix', complement: 'birthday_candles', category: 'food' },
  { primary: 'eggs', complement: 'milk', category: 'food' },
  { primary: 'coffee', complement: 'milk', category: 'food' },
  { primary: 'salad_greens', complement: 'avocado', category: 'food' },
  { primary: 'salmon', complement: 'olive_oil', category: 'food' },
  { primary: 'frying_pan', complement: 'utensil_set', category: 'home' },
  { primary: 'chef_knife', complement: 'cutting_board', category: 'home' },
  { primary: 'monitor', complement: 'laptop_stand', category: 'electronics' },
  { primary: 'keyboard', complement: 'gaming_mouse', category: 'electronics' },
  { primary: 'wireless_earbuds', complement: 'power_bank', category: 'electronics' },
  { primary: 'sweater', complement: 'chinos', category: 'fashion' },
  { primary: 'boots', complement: 'jeans', category: 'fashion' },
  { primary: 'pain_reliever', complement: 'vitamin_c', category: 'pharmacy' },
];

export function getProductById(id: string): Product | undefined {
  return allProducts.find(p => p.id === id);
}

export function getProductsByIds(ids: string[]): Product[] {
  return ids.map(id => getProductById(id)).filter((p): p is Product => p !== undefined);
}

export function getRelatedProducts(canonicalType: string): Product[] {
  const pairs = relationshipPairs.filter(
    p => p.primary === canonicalType || p.complement === canonicalType
  );
  const relatedTypes = pairs.map(p => 
    p.primary === canonicalType ? p.complement : p.primary
  );
  return allProducts.filter(p => relatedTypes.includes(p.canonicalType));
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return allProducts.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.brand.toLowerCase().includes(lowerQuery) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery)) ||
    p.category.toLowerCase().includes(lowerQuery) ||
    p.subcategory.toLowerCase().includes(lowerQuery)
  );
}
